// Mock data para desarrollo sin backend

export const mockUser = {
  id: "1",
  email: "demo@fitness.com",
  name: "Usuario Demo",
  profile: {
    age: 25,
    weight: 70,
    height: 175,
    goal: "muscle_gain" as const,
    experience: "intermediate" as const,
    equipment: ["dumbbells", "barbell", "bench"] as string[],
  },
}

export const mockRoutine = {
  id: "1",
  userId: "1",
  weekPlan: [
    {
      day: "Lunes",
      focus: "Pecho y Tríceps",
      exercises: [
        {
          id: "1",
          name: "Press de Banca",
          sets: 4,
          reps: "8-10",
          rest: 90,
          notes: "Controla el descenso, explosivo en la subida",
          muscleGroup: "Pecho",
          equipment: "Barra",
        },
        {
          id: "2",
          name: "Press Inclinado con Mancuernas",
          sets: 3,
          reps: "10-12",
          rest: 60,
          notes: "Mantén los codos a 45 grados",
          muscleGroup: "Pecho Superior",
          equipment: "Mancuernas",
        },
        {
          id: "3",
          name: "Fondos en Paralelas",
          sets: 3,
          reps: "hasta el fallo",
          rest: 60,
          notes: "Inclínate hacia adelante para trabajar pecho",
          muscleGroup: "Pecho Inferior",
          equipment: "Peso Corporal",
        },
        {
          id: "4",
          name: "Extensiones de Tríceps",
          sets: 3,
          reps: "12-15",
          rest: 45,
          notes: "Solo mueve el antebrazo",
          muscleGroup: "Tríceps",
          equipment: "Mancuerna",
        },
      ],
    },
    {
      day: "Martes",
      focus: "Espalda y Bíceps",
      exercises: [
        {
          id: "5",
          name: "Dominadas",
          sets: 4,
          reps: "6-8",
          rest: 90,
          notes: "Agarre pronado, ancho de hombros",
          muscleGroup: "Espalda",
          equipment: "Barra",
        },
        {
          id: "6",
          name: "Remo con Barra",
          sets: 4,
          reps: "8-10",
          rest: 75,
          notes: "Mantén la espalda recta",
          muscleGroup: "Espalda Media",
          equipment: "Barra",
        },
        {
          id: "7",
          name: "Curl con Barra",
          sets: 3,
          reps: "10-12",
          rest: 60,
          notes: "Sin balanceo, movimiento controlado",
          muscleGroup: "Bíceps",
          equipment: "Barra",
        },
        {
          id: "8",
          name: "Curl Martillo",
          sets: 3,
          reps: "10-12",
          rest: 45,
          notes: "Agarre neutral",
          muscleGroup: "Bíceps y Antebrazo",
          equipment: "Mancuernas",
        },
      ],
    },
    {
      day: "Miércoles",
      focus: "Descanso Activo",
      exercises: [
        {
          id: "9",
          name: "Caminata Ligera",
          sets: 1,
          reps: "30 min",
          rest: 0,
          notes: "Mantén un ritmo cómodo",
          muscleGroup: "Cardio",
          equipment: "Ninguno",
        },
      ],
    },
    {
      day: "Jueves",
      focus: "Piernas",
      exercises: [
        {
          id: "10",
          name: "Sentadilla con Barra",
          sets: 4,
          reps: "8-10",
          rest: 120,
          notes: "Profundidad completa, rodillas alineadas",
          muscleGroup: "Cuádriceps",
          equipment: "Barra",
        },
        {
          id: "11",
          name: "Peso Muerto Rumano",
          sets: 4,
          reps: "8-10",
          rest: 90,
          notes: "Siente el estiramiento en isquiotibiales",
          muscleGroup: "Isquiotibiales",
          equipment: "Barra",
        },
        {
          id: "12",
          name: "Zancadas",
          sets: 3,
          reps: "12 por pierna",
          rest: 60,
          notes: "Rodilla no pasa la punta del pie",
          muscleGroup: "Piernas Completas",
          equipment: "Mancuernas",
        },
        {
          id: "13",
          name: "Elevaciones de Pantorrilla",
          sets: 4,
          reps: "15-20",
          rest: 45,
          notes: "Rango completo de movimiento",
          muscleGroup: "Pantorrillas",
          equipment: "Mancuerna",
        },
      ],
    },
    {
      day: "Viernes",
      focus: "Hombros y Core",
      exercises: [
        {
          id: "14",
          name: "Press Militar",
          sets: 4,
          reps: "8-10",
          rest: 90,
          notes: "Barra frente al cuerpo",
          muscleGroup: "Hombros",
          equipment: "Barra",
        },
        {
          id: "15",
          name: "Elevaciones Laterales",
          sets: 3,
          reps: "12-15",
          rest: 60,
          notes: "Codos ligeramente flexionados",
          muscleGroup: "Hombros Laterales",
          equipment: "Mancuernas",
        },
        {
          id: "16",
          name: "Plancha",
          sets: 3,
          reps: "60 seg",
          rest: 60,
          notes: "Cuerpo recto, core contraído",
          muscleGroup: "Core",
          equipment: "Peso Corporal",
        },
        {
          id: "17",
          name: "Abdominales con Peso",
          sets: 3,
          reps: "15-20",
          rest: 45,
          notes: "Movimiento controlado",
          muscleGroup: "Abdominales",
          equipment: "Mancuerna",
        },
      ],
    },
  ],
  createdAt: new Date().toISOString(),
}

export const mockNutritionPlan = {
  id: "1",
  userId: "1",
  dailyCalories: 2500,
  macros: {
    protein: 180,
    carbs: 280,
    fats: 70,
  },
  meals: [
    {
      name: "Desayuno",
      time: "7:00 AM",
      calories: 600,
      foods: [
        { name: "Avena", quantity: "80g", calories: 300, protein: 10, carbs: 54, fats: 6 },
        { name: "Plátano", quantity: "1 unidad", calories: 105, protein: 1, carbs: 27, fats: 0 },
        { name: "Mantequilla de maní", quantity: "2 cdas", calories: 190, protein: 8, carbs: 7, fats: 16 },
        { name: "Proteína en polvo", quantity: "1 scoop", calories: 120, protein: 25, carbs: 3, fats: 1 },
      ],
    },
    {
      name: "Almuerzo",
      time: "1:00 PM",
      calories: 800,
      foods: [
        { name: "Pechuga de pollo", quantity: "200g", calories: 330, protein: 62, carbs: 0, fats: 7 },
        { name: "Arroz integral", quantity: "150g", calories: 180, protein: 4, carbs: 38, fats: 1 },
        { name: "Brócoli", quantity: "150g", calories: 50, protein: 4, carbs: 10, fats: 0 },
        { name: "Aguacate", quantity: "1/2 unidad", calories: 120, protein: 1, carbs: 6, fats: 11 },
      ],
    },
    {
      name: "Merienda Pre-Entreno",
      time: "4:30 PM",
      calories: 300,
      foods: [
        { name: "Pan integral", quantity: "2 rebanadas", calories: 160, protein: 8, carbs: 28, fats: 2 },
        { name: "Mermelada", quantity: "1 cda", calories: 50, protein: 0, carbs: 13, fats: 0 },
        { name: "Banana", quantity: "1 unidad", calories: 105, protein: 1, carbs: 27, fats: 0 },
      ],
    },
    {
      name: "Cena",
      time: "7:30 PM",
      calories: 700,
      foods: [
        { name: "Salmón", quantity: "150g", calories: 280, protein: 34, carbs: 0, fats: 16 },
        { name: "Batata", quantity: "200g", calories: 180, protein: 4, carbs: 41, fats: 0 },
        { name: "Espinaca", quantity: "100g", calories: 23, protein: 3, carbs: 4, fats: 0 },
        { name: "Aceite de oliva", quantity: "1 cda", calories: 120, protein: 0, carbs: 0, fats: 14 },
      ],
    },
    {
      name: "Snack Nocturno",
      time: "10:00 PM",
      calories: 200,
      foods: [
        { name: "Yogurt griego", quantity: "150g", calories: 100, protein: 17, carbs: 6, fats: 0 },
        { name: "Almendras", quantity: "20g", calories: 115, protein: 4, carbs: 4, fats: 10 },
      ],
    },
  ],
  shoppingList: [
    "Avena (1kg)",
    "Plátanos (7 unidades)",
    "Mantequilla de maní (500g)",
    "Proteína en polvo",
    "Pechuga de pollo (1.5kg)",
    "Arroz integral (1kg)",
    "Brócoli (1kg)",
    "Aguacates (4 unidades)",
    "Pan integral (1 paquete)",
    "Salmón (800g)",
    "Batatas (1.5kg)",
    "Espinaca (500g)",
    "Yogurt griego (1L)",
    "Almendras (200g)",
  ],
}

export const mockProgress = {
  measurements: [
    { date: "2024-01-01", weight: 72, bodyFat: 18 },
    { date: "2024-01-15", weight: 71.5, bodyFat: 17.5 },
    { date: "2024-02-01", weight: 71, bodyFat: 17 },
    { date: "2024-02-15", weight: 70.5, bodyFat: 16.5 },
    { date: "2024-03-01", weight: 70, bodyFat: 16 },
  ],
  workoutStats: {
    totalWorkouts: 32,
    totalSets: 480,
    totalVolume: 24500,
    averageIntensity: 7.5,
  },
}
